apiVersion: v1
kind: Service
metadata:
  name: phart-test-redis-service
  labels:
    username: phart
    env: test
spec:
  type: ClusterIP
  selector:
    app: phart-test-redis
  ports:
  - name: phart-redis
    port: 6379
    targetPort: 6379
