---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-phart-test
  labels:
    username: phart
    env: test
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: rbd
  resources:
    requests:
      storage: 1Gi
