version: '3'
services:
    web:
        build: .
        container_name: phart_hw04
        ports:
           - 5012:5000
        volumes:
           - ./data/animals.json:/animals.json
    redis:
        image: redis:latest
        ports:
            - 6392:6379
        volumes:
            - ./config/redis.conf:/redis.conf
        command: [ "redis-server", "/redis.conf" ]
