---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phart-hw7-worker-deployment
  labels:
    app: phart-hw7-worker
    username: phart
    env: test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phart-hw7-worker
  template:
    metadata:
      labels:
        app: phart-hw7-worker
        username: phart
        env: test
    spec:
      containers:
        - name: worker-container
          imagePullPolicy: Always
          image: phart26/phart-hw7
          env:
            - name: "WORKER_IP"
              valueFrom:
                fieldRef: 
                  fieldPath: status.podIP
          ports:
          - name: http
            containerPort: 5000 
