---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phart-hw7-worker-deployment
  labels:
    username: phart
    env: test
    app: phart-hw7-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phart-hw7-worker
  template:
    metadata:
      labels:
        app: phart-hw7-worker
    spec:
      containers:
        - name: worker-container
          imagePullPolicy: Always
          image: phart26/phart-hw7
          command: ['python', 'api.py']
