---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: phart-hw7-flask-deployment
  labels:
    app: phart-hw7-flask
spec:
  replicas: 1
  selector:
    matchLabels:
      app: phart-hw7-flask
  template:
    metadata:
      labels:
        app: phart-hw7-flask
    spec:
      containers:
        - name: flask-container
          imagePullPolicy: Always
          image: phart26/phart-hw7
          command: ['python', 'api.py']
          env:
          - name: FLASK_APP
            value: "api.py"
          ports:
          - name: http
            containerPort: 5000

